# Generated by Django 6.1.1 on 2026-09-10 17:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentOnboardingProfile",
            fields=[
                (
                    "student_unique_identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique UUIDv4 identifying the student.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_full_name",
                    models.CharField(help_text="Full legal name of the student.", max_length=100),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Student date of birth (must be between 3 and 18 years old)."
                    ),
                ),
                (
                    "parent_full_name",
                    models.CharField(
                        help_text="Full legal name of the primary parent or legal guardian.",
                        max_length=100,
                    ),
                ),
                (
                    "parent_email_address",
                    models.EmailField(
                        help_text="Verified contact email address of the parent.", max_length=254
                    ),
                ),
                (
                    "parent_phone_number",
                    models.CharField(
                        help_text="E.164 formatted international contact number of the parent.",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact_full_name",
                    models.CharField(
                        help_text="Full legal name of the secondary emergency contact.",
                        max_length=100,
                    ),
                ),
                (
                    "emergency_contact_phone_number",
                    models.CharField(
                        help_text="E.164 formatted international emergency contact number.",
                        max_length=20,
                    ),
                ),
                (
                    "primary_learning_support_category",
                    models.CharField(
                        choices=[
                            ("AUTISM_SPECTRUM_DISORDER", "Autism Spectrum Disorder"),
                            (
                                "ATTENTION_DEFICIT_HYPERACTIVITY_DISORDER",
                                "Attention Deficit Hyperactivity Disorder",
                            ),
                            (
                                "DYSLEXIA_AND_LITERACY_DIFFICULTIES",
                                "Dyslexia and Literacy Difficulties",
                            ),
                            ("SPEECH_AND_LANGUAGE_IMPAIRMENT", "Speech and Language Impairment"),
                            (
                                "GENERAL_COGNITIVE_DEVELOPMENTAL_DELAY",
                                "General Cognitive Developmental Delay",
                            ),
                        ],
                        help_text="Accredited diagnostic classification domain.",
                        max_length=60,
                    ),
                ),
                (
                    "assigned_learning_support_assistant_identifier",
                    models.EmailField(
                        help_text="Email of the assigned Learning Support Assistant.",
                        max_length=254,
                    ),
                ),
                (
                    "regional_jurisdiction",
                    models.CharField(
                        choices=[
                            ("DUBAI", "Dubai Educational District"),
                            ("ABU_DHABI", "Abu Dhabi Educational District"),
                            ("SHARJAH", "Sharjah Educational District"),
                            ("NORTHERN_EMIRATES", "Northern Emirates Educational District"),
                        ],
                        help_text="Geographical regulatory school district.",
                        max_length=50,
                    ),
                ),
                (
                    "dcyn_has_prior_formal_diagnosis",
                    models.BooleanField(
                        default=False, help_text="DCYN: Formally certified diagnosis on record."
                    ),
                ),
                (
                    "dcyn_requires_one_on_one_support",
                    models.BooleanField(
                        default=False, help_text="DCYN: Dedicated one-on-one LSA requirement."
                    ),
                ),
                (
                    "dcyn_has_individualized_education_plan",
                    models.BooleanField(
                        default=False, help_text="DCYN: Active Individualized Education Plan (IEP)."
                    ),
                ),
                (
                    "dcyn_requires_non_verbal_communication_assistance",
                    models.BooleanField(
                        default=False,
                        help_text="DCYN: Augmentative/Alternative communication requirement.",
                    ),
                ),
                (
                    "dcyn_has_physical_mobility_assistance_needs",
                    models.BooleanField(
                        default=False, help_text="DCYN: Wheelchair or classroom mobility needs."
                    ),
                ),
                (
                    "dcyn_is_independently_toilet_trained",
                    models.BooleanField(
                        default=False, help_text="DCYN: Bathroom independence verified."
                    ),
                ),
                (
                    "dcyn_has_sensory_sensitivity_triggers",
                    models.BooleanField(
                        default=False, help_text="DCYN: Severe sensory sensitivity indicators."
                    ),
                ),
                (
                    "dcyn_parental_data_processing_consent_granted",
                    models.BooleanField(
                        default=False,
                        help_text="DCYN: Verified legal consent under UAE data privacy regulations.",
                    ),
                ),
                (
                    "dcyn_emergency_medical_action_plan_available",
                    models.BooleanField(
                        default=False,
                        help_text="DCYN: Emergency pediatric medical action plan verified.",
                    ),
                ),
                (
                    "dcyn_transportation_assistance_required",
                    models.BooleanField(
                        default=False,
                        help_text="DCYN: Special vehicle transit accommodations needed.",
                    ),
                ),
                (
                    "ingestion_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="UTC timestamp of ingestion into the system.",
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="v1.0.0",
                        editable=False,
                        help_text="Version of the enforced schema contract.",
                        max_length=10,
                    ),
                ),
                (
                    "data_payload_sha256_hash",
                    models.CharField(
                        editable=False,
                        help_text="Cryptographic SHA-256 hash of original raw JSON payload.",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Onboarding Profile",
                "verbose_name_plural": "Student Onboarding Profiles",
                "db_table": "student_onboarding_profiles",
                "ordering": ["-ingestion_timestamp"],
            },
        ),
    ]
